export enum ErrorCode {
  // Common Errors
  INTERNAL_SERVER_ERROR = 'COMMON_001',
  BAD_REQUEST = 'COMMON_002',
  UNAUTHORIZED = 'COMMON_003',
  FORBIDDEN = 'COMMON_004',
  NOT_FOUND = 'COMMON_005',
  VALIDATION_ERROR = 'COMMON_006',

  // Auth Service (AUTH_*)
  AUTH_INVALID_CREDENTIALS = 'AUTH_001',
  AUTH_EMAIL_ALREADY_EXISTS = 'AUTH_002',
  AUTH_ACCOUNT_NOT_VERIFIED = 'AUTH_003',
  AUTH_TOKEN_EXPIRED = 'AUTH_004',
  AUTH_TOKEN_INVALID = 'AUTH_005',

  // Marketplace Service (PRODUCT_*)
  PRODUCT_NOT_FOUND = 'PRODUCT_001',
  PRODUCT_INSUFFICIENT_STOCK = 'PRODUCT_002',
  PRODUCT_INACTIVE = 'PRODUCT_003',

  // Order Service (ORDER_*)
  ORDER_NOT_FOUND = 'ORDER_001',
  ORDER_ALREADY_PAID = 'ORDER_002',
  ORDER_PAYMENT_FAILED = 'ORDER_003',

  // Investment Service (INVEST_*)
  INVEST_PROPOSAL_NOT_FOUND = 'INVEST_001',
  INVEST_MINIMUM_AMOUNT_NOT_MET = 'INVEST_002',
  INVEST_OVER_FUNDING = 'INVEST_003',
}
